var modernfamily = [
    {
        name:       "Phil Dunphy"
        , image:    "http://t1.gstatic.com/images?q=tbn:ANd9GcR3MQ61h4flFT49YacefQA"
            + "CXW-PhW_L3iAPh7BziXdTg1kd4TEN"
        , link:     "http://www.tvfanatic.com/quotes/characters/phil-modern-family/"
        , quotes:   [
            "I'm the cool dad. That's my thing. I'm hip. I surf the Web. I text."
                + "<br />LOL: laughing out loud. OMG: Oh my God. WTF: Why the face?"
                + "Um you know, I know all the dances to High School Musical so.."
            , "Act like a parent, talk like a peer. I call it peerenting. I learned"
                + " it from my own dad who used to walk into my room and say, "
                + "\"What's up sweat-hog?\""
            , "Well, yeah, until you sweep too much under the rug. Then you have a "
                + "lumpy rug…creates a tripping hazard…and open yourself up to "
                + "lawsuits."
            , "Are you kidding me? I love it. It's so creative - coupons for hugs, "
                + "which are usually free, but this makes it official, which is so "
                + "great."
            , "I am brave. Roller coasters? Love 'em. Scary movies? I’ve seen "
                + "Ghostbusters like 7 times.<br />I regularly drive through "
                + "neighborhoods that have only recently been gentrified."
            , "Um, well you know how in a fairy tale there's always a potion that "
                + "makes the princess fall asleep and then the guys start kissing "
                + "her?<br />Well, this is like that, except you don't wake up in a"
                + " castle - you wake up in a frat house with a bad reputation."
            , "This is so much better than cheesy garlic bread."
            , "You know what? You can insult a lot of things about me: my hair, my "
                + "voice, my balance-board exercises, but don't insult my selling. "
                + "<br />That crosses a line. What line? Oh, you don't see it?<br />"
                + "That's 'cause I just sold it."
            , "This is my fault. You see me achieve excellence and it puts a lot of "
                + "pressure on you."
            , "Gather round like you're hugging me, but don't touch me!"
            , "Forgive me for thinking your zesty performance deserves some praise!"
            , "What people do in the privacy of their own sports arena should be "
                + "their own business."
            , "Ho Ho Hold up a sec!"
            , "Did I just say wife gets in the way? Cause sometimes I do that."
            , "You're worried about germs? I've seen you kiss a pigeon on the mouth."
            , "With all you do for me, including going to the gym four times a week "
                + "to keep me interested, I got this."
            , "I know I got a lot of baggage, but don't worry, I'm seeing a "
                + "therapist.<br />Just kidding. I'm fine."
            , "Perhaps I'll be Reginald Appleby. An English gentleman in town for a "
                + "polo match."
            , "In your face, girl with a negative tattoo."
            , "I remember the speech that won me treasurer of my high school "
                + "spanish club. \"Mi nombre es filipe.\""
            , "Claire, we're not your parents; we're in much better shape."
            , "I know the pain is fresh, but the lie is really old."
            , "I'm usually good at catching things from women in bars."
            , "There she is. The prettiest white woman on Maui."
            , "Just to be clear, I'm not condoning eating your kids, but I sure "
                + "as heck know why giraffes do it."
            , "Claire likes to say \"You can be part of the problem, or part of "
                + "the solution.\" But I happen to believe you can be both"
            , "My boy was in trouble. So I put my fears aside and came to his "
                + "rescue? Does that make me a hero? Yes it does."
            , "Sad face emoticon! I can feel the hurt through the phone!"
            , "I called the florist and order one dozen Mylar balloons. Good "
                + "luck staying mad, honey!"
            , "Angela Lansbury was the grand marshal. Good times she wrote."
            , "You can kiss my wife, you can take her to bed, but only I can "
                + "make her laugh."
            , "Some voters find Claire angry and unlikeable. To those voters "
                + "I would say...wait till she reads this."
            , "Let's dim the lights, crank up Norah Jones and get this over with."
            , "Quick, what's my favorite hospital food? Jellooo."
            , "I know you were reluctant to get that massage, but I think we "
                + "can both agree it had a happy ending."
            , "I've always said that if my son thinks of me as one of his idiot "
                + "friends, I've succeeded as a dad."
            , "Guess it's just one of those things that we'll never know, like "
                + "what really happened to the Titanic."
            , "\"My wife won't let me go to Vegas.\" Trust me that is not a "
                + "phone call you want to make to a group of ex-college male "
                + "cheerleaders.<br />They will mock you with a hurtful rhythmic "
                + "taunt."
            , "I think the carpet matches the drapes, I haven't checked in a while."
            , "I love Westerns, the bloodier the better, that's my favorite type "
                + "of movie - that and anything set against the backdrop of "
                + "competitive cheerleading."
            , "Whoa, whoa, maybe it's all the creams, that just made sense, "
                + "girlfriends."
            , "All those joke emails she forwarded to me months after I'd seen "
                + "them? Well, no more polite LOLs for YOU, Dede."
            , "We were, as they say, having sex."
            , "Why do I have to watch a French movie, I didn't do anything wrong."
            , "Luke, I am your father. That's what I said to you when you were "
                + "coming out of your mom's lady parts."
            , "Yeah, he gives me a hard time. But that's the deal with a "
                + "father-in-law. The key is I never let him see just how much it "
                + "devastates me."
        ]
    }
    , {
        name:       "Claire Dunphy"
        , image:    "http://t3.gstatic.com/images?q=tbn:ANd9GcRJHIq3QbCQwPhgGkJTHHwYh"
            + "xNOGzw644fGXzdPGRPAYLXXDsLH"
        , link:     "http://www.tvfanatic.com/quotes/characters/claire-modern-family/"
        , quotes:   [
            "Sure I had a little peppermint schnapps at my prom but I kicked my "
                + "boyfriend out before my parents woke up. It's called respect."
            , "If she's going to leave the nest, we'd prefer it's not on the back "
                + "of a motorcycle."
            , "I told you that I would do everything possibly to make sure that "
                + "your skeleton ends up in a science class at a women's college."
            , "Doesn't he know that tiptoeing around someone like they're crazy, "
                + "actually makes them crazy?"
            , "I can be spontaneous every 4 years."
            , "Honey don't you think it's weird that one of your friends is an "
                + "80-year-old man?"
            , "I just wanted to spend my night with some fun gay people. It's not "
                + "my fault this one decided to be straight!"
            , "I want music and dancing and secondhand smoke!"
            , "I have 3 kids, I've been tired since 2005."
            , "I take my eye off the ball for one minute and I've got one kid in a "
                + "coma, one with a black eye, and one running a crime ring."
            , "Sweetheart I would love to be wrong, but I don't live with the "
                + "right people for that."
            , "Kids these days get trophies just for showing up. What's that gonna "
                + "lead to? A bunch of thirty year olds living at home."
            , "He was two, and all he could do was bark."
            , "Sweetie we did it! Our baby is average!"
            , "I had to undress a mannequin while a creepy guy filmed it, so we "
                + "have that to look forward to on the Internet."
            , "Am I a bad enough parent to ignore that?"
            , "We need a game plan, we need to map out exactly what we are going "
                + "to say, because that is the only way I will be able to hold it "
                + "together while our babies look at us with judgEment and disgust."
            , "That's not a euphemism. That's actually what we were doing."
            , "It's an obsessive-compulsive thing. I have read like a hundred "
                + "articles about it."
            , "You can't have two fun parents...<br />You know that kid Liam who "
                + "wears pajama pants to school and pays for things with a "
                + "hundred-dollar bill? Two fun parents."
            , "Honey, trust me, I'm sparing you an entire day of guys asking you "
                + "if you have a rough tongue."
            , "Don't take this the wrong way, but I have almost no faith in you."
            , "Your kids don't need to know who you were before you had them; they "
                + "need to know who you wish you were, and try to live up to that "
                + "person.<br />They're gonna fall short, but better they fall "
                + "short of the fake you than the real you."
            , "Women in their 30s on the internet are like ninjas. They get in "
                + "their little, black outfits and try to sneak their way into "
                + "your marriage."
            , "I have this theory that Phil purposely installs complicated "
                + "technology so he has a reason to talk to me like I'm a child."
            , "Luke already is the best at something. Being my son ...<br />"
                + "That sounded a lot less lame in my head."
            , "If I say something that everybody else is thinking, does that make "
                + "me a mean person? Or, does it make me a brave person, one who "
                + "is courageous enough to stand up and say something, behind "
                + "someone's back to a ten-year-old?"
            , "You know how growing up we all have that voice inside our head that "
                + "tells us we're not good enough?<br />Well, mine was outside my "
                + "head driving me to school"
            , "It's way too short. People know you're a girl; you don't need to "
                + "prove it to them."
            , "One minute you're just friends watching Falcon Crest and the next, "
                + "you're lying underneath the air hockey table with your bra in "
                + "your pocket"
        ]
    }
    , {
        name:       "Jay Pritchett"
        , image:    "http://static.tvfanatic.com/images/videos/modern-family-"
            + "season-4-promo_100x80.jpg"
        , link:     "http://www.tvfanatic.com/quotes/characters/jay-modern-family/"
        , quotes:   [
            "Do you know how much walking you have to do at Disneyland? Why do you "
                + "think they have so many fat people on scooters?"
            , "What do you say? Anybody up for a hobo adventure?"
            , "How do I say this without sounding like an ass? I'm kind of a "
                + "legend to these guys."
            , "Remember that time I told you I couldn't make your figure skating "
                + "competition because I was stuck at work?<br /><br />By stuck I "
                + "meant drunk and by work I meant the golf course!"
            , "I can't express to you how badly this kid needs football."
            , "Sometimes the best thing to do in a race to the top is grease the "
                + "pole behind you."
            , "Hey what do you say we cut our losses? Let's go out to a nice "
                + "Chinese restaurant and have a traditional Jewish Christmas."
            , "You two needed time with your mom, I've already served time with "
                + "your mom."
            , "Now, the old Jay would have said, 'I wanted to be on a lake with "
                + "a fishing rod and sunshine. Not bobbing around at night in a "
                + "swimming pool.' I miss the old Jay."
            , "Sausage-of-the-month club really nailed it in May, but honey, no "
                + "offense, they almost lost me last month with that chorizo."
            , "How much longer do I have to listen to the Julia Child impression?"
            , "I'm gonna walk like a man... right to that bar.<br />That would be "
                + "hilarious if you were familiar with Frankie Valli."
            , "I was drunk, I'm not going shopping with Priscilla Queen of the "
                + "Desert."
            , "There's enough not to like about death without adding dirt and "
                + "worms."
            , "You know, when you get a massage, you sound like a Tijuana "
                + "prostitute."
            , "You'd think growing up in a place full of death squads and drunken "
                + "uncles, she'd have learned to move a little bit faster."
            , "I'm just saying you were never much of a kid. And that's a good "
                + "thing 'cause I never liked kids."
            , "I don't get how one dog keeps you awake when you grew up sleeping "
                + "through cockfights and revolutions."
            , "She's always had a certain comfort level with... killing."
            , "Don't be coy, what are you waiting for a box of chocolates? Let's "
                + "do this!"
            , "I just ordered an extra-long straw to avoid accidentally doing a "
                + "sit-up"
            , "You want scary? When I was his age I lived through the Cuban "
                + "Missile Crisis. I slept with a butter knife under my pillow in "
                + "case I had to fight some Soviet colonel."
            , "I only understand about 20% of what goes on around here."
            , "I mean, for me it's a locker room. For him, it's a showroom."
            , "We're guys, we don't open up. We talk about sports and cars and "
                + "getting up in the middle of the night to pee."
            , "Here's the deal. Girls don't go for all that romantic stuff. They "
                + "go for power and success. And since you don't have either one "
                + "of those things, you're gonna be the funny guy."
            , "I had a buddy that went to Woodstock, believed he could fly, didn't "
                + "end great. That's why hotels' windows don't open anymore"
            , "I don't like watching football with people that don't care about "
                + "the game, they talk."
            , "90 percent of being a dad is just showing up."
        ]
    }
    , {
        name:       "Gloria Delgado-Pritchett"
        , image:    "http://static.tvfanatic.com/images/gallery/gloria-photo_"
            + "167x250.jpg"
        , link:     "http://www.tvfanatic.com/quotes/characters/gloria-modern-family/"
        , quotes:   [
            "I don't wanna be around when something that tight unravels."
            , "There are blind models? That's so sad, they can't see how pretty "
                + "they are!"
            , "It's a freakshow, but it's their freakshow."
            , "I know you can't tell by looking at me, but I'm not a natural "
                + "homemaker."
            , "That's when you know your family loves you, when they feel free to "
                + "scream at you."
            , "Are you happy? You have reduced me to a person who eats a shoe."
            , "I don't have all day to describe my meals to you."
            , "Where I come from, brothers respect each other."
            , "Ta-da is for when you do a flip or where the magician cuts the "
                + "pretty lady in half, not when you show someone where you want "
                + "to shove their dead body."
            , "In Colombia, you can't go to the hospital for every little sniffle "
                + "or dislocated shoulder."
            , "That doesn't make any sense! Who wants to live in a world where "
                + "dogs eat each other? Doggy-dog world is a beautiful world "
                + "filled with little poh-pees."
            , "He scared the baby cheeses out of me!"
            , "Oh, here we go, because in Colombia we trip over goats and we kill "
                + "people in the street! Do you know how offensive that is? Like "
                + "we're Peruvians!"
            , "I'm Columbian, I know a fake crime scene when I see one."
            , "He comes from a long line of fishers and smugglers. But I encourage "
                + "the fishing."
            , "I come from a neighborhood with a lot of prostitutes."
            , "This is not art. This is an unholy mix between man and beast."
            , "Children need to know that you believe in them; it's the most "
                + "important thing. If you tell them they have wings, they will "
                + "believe they can fly."
        ]
    }
    , {
        name:       "Mitchell Pritchett"
        , image:    "http://static.tvfanatic.com/images/gallery/jesse-tyler-"
            + "ferguson-as-mitchell_200x264.jpg"
        , link:     "http://www.tvfanatic.com/quotes/characters/mitchell-modern-family/"
        , quotes:   [
            "How cool would it be if you turned into Wonder Woman right now?"
            , "You can't get fired from a favor!"
            , "I haven't been judged by this many people since I forgot my canvas "
                + "bags at Whole Foods."
            , "A month after the most devastating twister to ever hit Cam's "
                + "hometown, I throw a party based on gay cinema's most famous "
                + "tornado."
            , "I don't know about you but I've got about five minutes of fabulous "
                + "left."
            , "You know I'm gonna check the lease, but I'm pretty sure we're not "
                + "allowed to have a meth lab."
            , "It happens to be mother's day. Not martyr's day."
            , "When I was 12-years-old my father walked into my bedroom and caught "
                + "me doing the most embarrassing thing that a boy can do: dancing "
                + "to Madonna's 'Lucky Star.'"
            , "I was wrong, every kid wants a clown for a dad."
            , "This could be my 'going bald' scare all over again."
            , "I once saw a picture of myself at a friend's poetry slam, and all "
                + "you could see were the whites of my eyes."
            , "You're like a mob wife. You complain about what I do, but have no "
                + "problem wearing the fur that fell off the back of the truck."
            , "Nobody kisses at a bowling alley!"
            , "Sweet Lady Gaga... that is good."
            , "I'm going to have to go talk it over with my bull in a china shop."
            , "Are we sure we're not exaggerating just a little bit?"
            , "He's the suckiest suck of all time."
            , "I am going to do what I am trained to do. I am going to lie, "
                + "grovel, debase myself until I get what I want. I am a lawyer, "
                + "damn it."
            , "Subtext: this is weird."
            , "Take it down a notch. We're just trying to make a friend not "
                + "initiate a three-way."
            , "I had to actually come out to my dad three times before he "
                + "acknowledged it. I'm not sure if maybe he was hoping he heard "
                + "it wrong, like I said 'Dad, I'm grey.'"
            , "People are who they are, give or take 15 percent. That's how much "
                + "people can change if they really want to."
            , "My gaydar is never wrong and it is pinging like we're at a bathhouse"
            , "He's like Batman, but straight."
            , "We were called \"Fire and Nice.\" I was \"Fire\" because of the red "
                + "hair and Claire was \"Nice\" because it was ironic and she "
                + "wasn't."
            , "I am loose. I'm fun. Remember breakfast for dinner last week? "
                + "My idea."
        ]
    }
    , {
        name:       "Cameron Tucker"
        , image:    "http://static.tvfanatic.com/images/gallery/cameron-and-lily.jpg"
        , link:     "http://www.tvfanatic.com/quotes/characters/cameron-modern-family/"
        , quotes:   [
            "Why don't you call my dad and talk about what a teet-sucking layabout "
                + "I am?"
            , "Is this kindergarten or the Hunger Games?"
            , "If you ever put your hands on my daughter again, I will string you "
                + "up by your feet, run you up the flagpole and let the birds peck "
                + "out your eyes."
            , "Oh I'm sorry are my pinkies up? They do that when I get excited. "
                + "Down girls."
            , "It's better to carry a tune than a grudge."
            , "It's hard to have a relationship and a clown career. That's the "
                + "reason there are so many single clowns."
            , "I'm playing a drinking game. It's called everytime I feel depressed "
                + "about something, I take a drink."
            , "I'm sorry but you know I have two weakness: children cursing and "
                + "old people rapping!"
            , "It's a somber occasion and all of my tops are too joyful."
            , "When I get home I'm gonna scrub this place like it's a crime scene, "
                + "which it is because you murdered joy."
            , "Get away from me temptress! And I never thought I'd call you that "
                + "in a negative way."
            , "Well now you've put me in an awkward position."
            , "Years from now some of these kids will still be talking about the "
                + "way I Sondheim-ized them."
            , "We are beyond blotting and rubbing, we've moved on to sweating and "
                + "crying."
            , "You don't tell your partner you may have a baby with someone else "
                + "and then go back to eating a delicious and inventive meal like "
                + "it's NOTHING!"
            , "Oh, the smiley face makes it okay! 'I waterboarded our toddler, "
                + "LOL!'"
            , "Missouri is more cosmopolitan than you give it credit for. It's got "
                + "a very vibrant cowboy poetry scene."
            , "You cheated on me with choreography and that is the worst kind."
            , "If I have to read The Very Hungry Caterpillar one more time, I "
                + "will snap!"
            , "Every home-improvement project we've undertaken has been a "
                + "near-death experience."
            , "I get it, you're terrfied of small talk and birds, you're just "
                + "lucky that pigeon didn't want to chat you up about the "
                + "weather."
            , "He was a very nice man when we met him, but based on his recent "
                + "letters I have a small fear he's become a war lord."
            , "I really, really, really just want him to get a job so I can go "
                + "back to being a stay-at-home dad/trophy wife."
            , "I was nervous. There was a lot of different food on the menu, "
                + "and on the floor and on the wall."
            , "We can't ignore the giant panda in the room"
            , "It's Valentine's Day. It's not the day you run away from love. "
                + "It's the day you chase it down."
            , "If I was home right now, I'd be mixing up a bathtub full of "
                + "eggnog and trying to squeeze a greased hog into a Santa "
                + "hat. You don't think I don't miss that?"
            , "If I wasn't in school or fishing, I was clowning. There are "
                + "four types of clowns: a tramp, Auguste, a whiteface, and "
                + "a character. I am a classically trained Auguste clown named "
                + "Fizbo."
            , "I'm the ass kicking clown that will twist you like a balloon animal!"
            , "You had to clip my wings which you used to be the wind beneath"
        ]
    }
    , {
        name:       "Alex Dunphy"
        , image:    "http://static.tvfanatic.com/images/gallery/ariel-winter-as-"
            + "alex_188x250.jpg"
        , link:     "http://www.tvfanatic.com/quotes/characters/alex-modern-family/"
        , quotes:   [
            "This family needs a dumbass-ectomy."
            , "Isn't there a fraternity you need to pass out in?"
            , "First get a mirror, then you're gonna look into it and you're gonna "
                + "see a crazy woman. She needs your help."
            , "You have your fans, I have mine. And one day, your fans are gonna "
                + "work for my fans."
            , "Could you L a little less O L? Can't you see what I'm trying to do "
                + "here?"
            , "I guess what I'm trying to say is, \"Don't stop believing. Get this "
                + "party started.\""
            , "You're never alone when you have books."
        ]
    }
];
