var modernfamily = [
    {
        name:       "Phil Dunphy"
        , image:    "http://t1.gstatic.com/images?q=tbn:ANd9GcR3MQ61h4flFT49YacefQA"
            + "CXW-PhW_L3iAPh7BziXdTg1kd4TEN"
        , link:     "http://www.tvfanatic.com/quotes/characters/phil-modern-family/"
        , quotes:   [
            "I'm the cool dad. That's my thing. I'm hip. I surf the Web. I text."
                + "<br />LOL: laughing out loud. OMG: Oh my God. WTF: Why the face?"
                + "Um you know, I know all the dances to High School Musical so.."
            , "Act like a parent, talk like a peer. I call it peerenting. I learned"
                + " it from my own dad who used to walk into my room and say, "
                + "\"What's up sweat-hog?\""
            , "Well, yeah, until you sweep too much under the rug. Then you have a "
                + "lumpy rug…creates a tripping hazard…and open yourself up to "
                + "lawsuits."
            , "Are you kidding me? I love it. It's so creative - coupons for hugs, "
                + "which are usually free, but this makes it official, which is so "
                + "great."
            , "I am brave. Roller coasters? Love 'em. Scary movies? I’ve seen "
                + "Ghostbusters like 7 times.<br />I regularly drive through "
                + "neighborhoods that have only recently been gentrified."
            , "Um, well you know how in a fairy tale there's always a potion that "
                + "makes the princess fall asleep and then the guys start kissing "
                + "her?<br />Well, this is like that, except you don't wake up in a"
                + " castle - you wake up in a frat house with a bad reputation."
            , "This is so much better than cheesy garlic bread."
            , "You know what? You can insult a lot of things about me: my hair, my "
                + "voice, my balance-board exercises, but don't insult my selling. "
                + "<br />That crosses a line. What line? Oh, you don't see it?<br />"
                + "That's 'cause I just sold it."
            , "This is my fault. You see me achieve excellence and it puts a lot of "
                + "pressure on you."
            , "Gather round like you're hugging me, but don't touch me!"
            , "Forgive me for thinking your zesty performance deserves some praise!"
            , "What people do in the privacy of their own sports arena should be "
                + "their own business."
            , "Ho Ho Hold up a sec!"
            , "Did I just say wife gets in the way? Cause sometimes I do that."
            , "You're worried about germs? I've seen you kiss a pigeon on the mouth."
            , "With all you do for me, including going to the gym four times a week "
                + "to keep me interested, I got this."
            , "I know I got a lot of baggage, but don't worry, I'm seeing a "
                + "therapist.<br />Just kidding. I'm fine."
            , "Perhaps I'll be Reginald Appleby. An English gentleman in town for a "
                + "polo match."
            , "In your face, girl with a negative tattoo."
            , "I remember the speech that won me treasurer of my high school "
                + "spanish club. \"Mi nombre es filipe.\""
            , "Claire, we're not your parents; we're in much better shape."
            , "I know the pain is fresh, but the lie is really old."
            , "I'm usually good at catching things from women in bars."
            , "There she is. The prettiest white woman on Maui."
            , "Just to be clear, I'm not condoning eating your kids, but I sure "
                + "as heck know why giraffes do it."
            , "Claire likes to say \"You can be part of the problem, or part of "
                + "the solution.\" But I happen to believe you can be both"
            , "My boy was in trouble. So I put my fears aside and came to his "
                + "rescue? Does that make me a hero? Yes it does."
            , "Sad face emoticon! I can feel the hurt through the phone!"
            , "I called the florist and order one dozen Mylar balloons. Good "
                + "luck staying mad, honey!"
            , "Angela Lansbury was the grand marshal. Good times she wrote."
            , "You can kiss my wife, you can take her to bed, but only I can "
                + "make her laugh."
            , "Some voters find Claire angry and unlikeable. To those voters "
                + "I would say...wait till she reads this."
            , "Let's dim the lights, crank up Norah Jones and get this over with."
            , "Quick, what's my favorite hospital food? Jellooo."
            , "I know you were reluctant to get that massage, but I think we "
                + "can both agree it had a happy ending."
            , "I've always said that if my son thinks of me as one of his idiot "
                + "friends, I've succeeded as a dad."
            , "Guess it's just one of those things that we'll never know, like "
                + "what really happened to the Titanic."
            , "\"My wife won't let me go to Vegas.\" Trust me that is not a "
                + "phone call you want to make to a group of ex-college male "
                + "cheerleaders.<br />They will mock you with a hurtful rhythmic "
                + "taunt."
            , "I think the carpet matches the drapes, I haven't checked in a while."
            , "I love Westerns, the bloodier the better, that's my favorite type "
                + "of movie - that and anything set against the backdrop of "
                + "competitive cheerleading."
            , "Whoa, whoa, maybe it's all the creams, that just made sense, "
                + "girlfriends."
            , "All those joke emails she forwarded to me months after I'd seen "
                + "them? Well, no more polite LOLs for YOU, Dede."
            , "We were, as they say, having sex."
            , "Why do I have to watch a French movie, I didn't do anything wrong."
            , "Luke, I am your father. That's what I said to you when you were "
                + "coming out of your mom's lady parts."
            , "Yeah, he gives me a hard time. But that's the deal with a "
                + "father-in-law. The key is I never let him see just how much it "
                + "devastates me."
        ]
    }
];