var muppets = [
    {
        name:       "Mr. Snuffleupagus"
        , image:    "http://images2.wikia.nocookie.net/__cb52637/muppet/"
            + "images/thumb/f/fc/Character.snuffy.jpg/"
            + "130px-0%2C479%2C9%2C433-Character.snuffy.jpg"
        , link:     "http://muppet.wikia.com/wiki/Mr._Snuffleupagus"
        , quotes:   [
            "Don't worry, Bird. We can hug for real when you get back to Sesame "
                + "Street."
            , "You could imagine that we're hugging, Bird."
            , "I wouldn't know, Bird. The only temple I've ever seen is Shirley "
                + "Temple"
            , "Now that we know how Santa gets *into* the chimney, how does he "
                + "get *out*?"
            , "That is because you are imagining me, Bird."
        ]
    }
    ,{
        name:       "Kermit the Frog"
        , image:    "http://images2.wikia.nocookie.net/__cb52637/muppet/"
            + "images/thumb/7/79/Kermit-the-frog.jpg/"
            + "130px-0%2C377%2C6%2C340-Kermit-the-frog.jpg"
        , link:     "http://muppet.wikia.com/wiki/Kermit_the_Frog"
        , quotes:   [
            "Someday we'll find it, the rainbow connection.<br />The lovers, the "
                + "dreamers, and me."
            , "Good grief, it's a running gag."
            , "Miss Piggy, you look beautiful!"
            , "It's too bad the dancing girls are on vacation. This crowd's "
                + "getting ugly."
            , "Gee"
            , "<i>[Looking at a map]</i><br />Well, let's see.<br />"
                + "We're just traveling down this little black line here, and uh, "
                + "just crossed that little red line over here"
            , "Frankly, Miss Piggy, I don't give a hoot."
            , "Yeah. But then it would just be me feeling miserable.<br />"
                + "Now I got a lady pig, and a bear and a chicken, a dog, a thing, "
                + "whatever Gonzo is.<br />He's a little like a turkey."
            , "That's Piggy!"
            , "Darn, I missed. You know that's the first thing to go on a frog?"
                + "<br />His tongue. The tongue goes and you can't catch flies."
            , "Do what I do: Imagine the audience naked."
            , "Listen everybody, we've got nothing to be ashamed of.<br /><br />"
                + "And you know why? Well because, thanks to Walter here we tried. "
                + "And if we failed, we failed together and to me that's not "
                + "failing at all.<br /><br />And I don't care what anybody says, "
                + "I don't care if no one believes in us because... <br /><br />"
                + "I believe. <br />I believe in you. <br />And you. <br />"
                + "And you. <br />You know what's important isn't this building or "
                + "name, it's each other. So I say fine, let's just start from the "
                + "bottom and work our way back up to the top. <br /><br />Let's "
                + "all walk out through these doors with our heads held up high, "
                + "as a family because that's what we are."
            , "Hey, hey just a second. How did you know about that 'toupe'?"
            , "I believe. <br />I believe in you. <br />And you. <br />"
                + "And you."
            , "<i>[whispering]</i> Piggy, I thought Gonzo was gonna play the "
                + "minister."
            , "Me? In love with a pig? Wait 'til I tell the guys in marketing."
            , "Maybe you expected me to go HOG-wild? Perhaps you could bring home "
                + "the BACON! <br /><br />Ahhh... the sounds of love: su-EEEEE! "
                + "Oink, oink!"
        ]
    }
    ,{
        name:       "Cookie Monster"
        , image:    "http://images1.wikia.nocookie.net/__cb52637/muppet/"
            + "images/thumb/f/f4/CookieMonster-Sitting.jpg/"
            + "130px-0%2C390%2C5%2C350-CookieMonster-Sitting.jpg"
        , link:     "http://muppet.wikia.com/wiki/Cookie_Monster"
        , quotes:   [
            "Me not *take* cookies, me *eat* the cookies."
            , "Eat begin with an E and take... Begin with a T."
            , "Me eat picture!"
            , "Let me eat frame"
            , "COOKIE!"
            , "Ohhh, ohh, oh, Scotch pine delicious, but Douglas fir give me "
                + "heartburn.<br /><br /> Burp! <br /><br />Excuse me, ohhh, oh!"
            , "Burp! Buuuuuuurrrp! Oh that a long one, buuuuurrp, buuuurrp, oh!"
            , "COOKIE!"
            , "Omm nom nom nom"
            , "C is for cookie! That's good enough for me!"
            , "That no letter O, that cookie."
            , "Sometime me think 'what is a friend?' and then me think... 'friend "
                + "is what last chocolate cookie is for.'"
        ]
    }
    ,{
        name:       "Beaker"
        , image:    "http://images4.wikia.nocookie.net/__cb52637/muppet/"
            + "images/thumb/0/05/Beaker.jpg/130px-0%2C300%2C4%2C269-Beaker.jpg"
        , link:     "http://muppet.wikia.com/wiki/Beaker"
        , quotes:   [
            "Mee mee moo meep meep mind."
            , "Meep?"
            , "MEEEEEEEEEEEEEEEEEP!"
        ]
    }
    ,{
        name:       "Elmo"
        , image:    "http://images1.wikia.nocookie.net/__cb52637/muppet/"
            + "images/thumb/5/5a/Elmo-elmo-elmo.jpg/"
            + "130px-0%2C800%2C13%2C721-Elmo-elmo-elmo.jpg"
        , link:     "http://muppet.wikia.com/wiki/Elmo"
        , quotes:   [
            "Ha ha ha! You're not Santa Claus, you're Cookie Monster!"
            , "Look Everybody! Elmo is a firefighter!"
            , "Heeheehee, that tickles!"
            , "Elmo loves you."
            , "Meee moo ma mi. Meee ma moo meeee. Lalamooomaaaamima."
        ]
    }
    ,{
        name:       "Miss Piggy"
        , image:    "http://images4.wikia.nocookie.net/__cb52637/muppet/"
            + "images/thumb/a/a1/Miss-piggy---the-muppets.png/"
            + "130px-0%2C916%2C15%2C825-Miss-piggy---the-muppets.png"
        , link:     "http://muppet.wikia.com/wiki/Miss_Piggy"
        , quotes:   [
            "Moi's hair has natural curls. So does my tail."
            , "I, moiself, have always enjoyed a good scrimmage."
            , "I am waiting for a really strong and meaningful female pig role."
            , "I hereby issue a writ of hocus-pocus."
            , "This, you see, is my ultimate ambition - to live a simple life "
                + "with the frog I love."
            , "Moi has always possessed a charm that is lethal to men"
            , "I plan to write more books whenever I can find the appropriate "
                + "writing attire and color-coordinated pen."
            , "Hello little people. What an absolutely splendid day"
            , "We're going to pause here and we'll be right back with Gonzo, the "
                + "Geek Who Fell to Earth."
            , "Midnight. <br /><br />The lone alien stands before a naked sky. "
                + "<br /><br />The mood is tense. <br /><br />"
                + "My hair looks <b><i>great</i></b>."
            , "You! It was you! Kermit was right!<br /><br />You're a phony. "
                + "You're a phony! <br /><br />Yes, you are! And you know what, "
                + "you can't even sing! Your voice was dubbed!"
            , "Oh, Kermy! Oh, I've missed you so!"
            , "Adios, mon cherie"
            , "Well, as you can see from this small sampling, modeling is my life. "
                + "It is my destiny, I shall accept nothing less."
            , "Will you hurry up? Don't make me miss my cue!"
            , "Will everybody stop singing different songs? <br /><br />"
                + "I can't remember which one I'm supposed to sing!<br /><br />"
                + "Oh yeah. Right. Bee-dooby doo..."
            , "How would you like a pork chop? Hi-yah!<br /><br />You always hurt"
                + "the one you love."
            , "Listen, high pockets, here's how things work in enchanted lands. "
                + "<br />Shoes have magical powers. If you have the shoes, you get "
                + "the powers. <br /><br />But if you're going to question every "
                + "little detail, the whole thing's gonna fall apart and we might "
                + "as well call it a day, okay?"
            , "Oh! Kermit, thank you for apologizing so sincerely and abjectly to "
                + "your lover pig."
        ]
    }
    ,{
        name:       "Gonzo"
        , image:    "http://images2.wikia.nocookie.net/__cb52637/muppet/"
            + "images/thumb/0/0c/Gonzo2011.png/"
            + "130px-0%2C966%2C14%2C869-Gonzo2011.png"
        , link:     "http://muppet.wikia.com/wiki/Gonzo"
        , quotes:   [
            "People of Earth, do not be alarmed!"
            , "I had that weird dream again."
            , "What am I? Oh, uh, good question. <br /><br />"
                + "Now technically speaking, uhh, let's say, put me down "
                + "as a... 'Whatever'?"
            , "Remember, I built this new Jacuzzi for my alien family, so "
                + "please, no eating in the spa."
            , "Well, it's just that I'm sick and tired of being a "
                + "one-of-a-kind freak, that's all."
            , "Now we can go meet my alien brothers at Cape Doom."
            , "That was probably the best day of my whole life. There's just "
                + "one thing I still don't understand.<br /><br />"
                + "Why did they ask me to build a jacuzzi?"
            , "Hello! <br /><br />Welcome to the Muppet Christmas Carol! "
                + "I am here to tell the story."
            , "I knew you weren't suited for literature."
            , "I told you, storytellers are omniscient; I know everything."
            , "To say that Scrooge became startled would be untrue. <br /><br />"
                + "Still the moment had passed, and the world was as it should be."
            , "The world will forever wonder who I am!"
        ]
    }
    ,{
        name:       "Big Bird"
        , image:    "http://images2.wikia.nocookie.net/__cb52637/muppet/"
            + "images/thumb/9/92/Bigbirdnewversion.png/"
            + "130px-0%2C325%2C7%2C295-Bigbirdnewversion.png"
        , link:     "http://muppet.wikia.com/wiki/Big_Bird"
        , quotes:   [
            "Hey, I've got a great idea. <br /><br />Let's play make-believe."
                + "<br /><br />I'll be Snow White."
            , "I said we just could make believe. You know, pretend?<br /><br />"
                + "Uh, use your imagination."
            , "But I don't want to hunt worms. I want Snuffy to come and visit. "
                + "And if he can't come and visit, I don't want to be here anymore."
                + " I want to go home!"
            , "Oh, I'm not a chicken actually. I'm a bird on the run.<br /><br />"
                + "I didn't run away. I'm going back to my real home on Sesame "
                + "Street where I belong."
            , "Well, it's so good to almost see you. <br />I suppose a hug is out "
                + "of the question, you being imaginary right now."
            , "Uh, you don't have a nickname, do you?"
            , "Well, he's got to come back. <br /><br />Why, who's going to take "
                + "care of the store? <br /><br />And who's going to make my "
                + "birdseed milkshakes, and tell me stories?"
            , "Well, I don't understand! You know everything was just fine.<br />"
                + "Why does it have to be this way? Give me one good reason!"
            , "I know how Santa gets down the chimney! <br /><br />All he does is "
                + "take that big belt of his and tie it real tight around his waist,"
                + " and it makes him so skinny he fits right down the chimney."
        ]
    }
    ,{
        name:       "Animal"
        , image:    "http://images4.wikia.nocookie.net/__cb52637/muppet/"
            + "images/thumb/7/78/AN_004.jpg/"
            + "130px-0%2C561%2C10%2C506-AN_004.jpg"
        , link:     "http://muppet.wikia.com/wiki/Animal"
        , quotes:   [
            "Beat drums! Beat drums!"
            , "DOWN!"
            , "I want to - eat drums!"
            , "Irritated! Irritated!"
            , "...Acting... Naturaaaal. <br /><br />In control."
            , "NAP TIME!"
        ]
    }
    ,{
        name:       "Fozzie Bear"
        , image:    "http://images1.wikia.nocookie.net/__cb52637/muppet/"
            + "images/thumb/f/fc/Fozzie_new.jpg/"
            + "130px-0%2C2400%2C39%2C2162-Fozzie_new.jpg"
        , link:     "http://muppet.wikia.com/wiki/Fozzie_Bear"
        , quotes:   [
            "If that's the Happiness Hotel, I'd hate to see what the sad one "
                + "looks like."
            , "I guess this would be a bad time to ask for a raise?"
            , "<i>[drinking champagne]</i> You know, if you put enough sugar in "
                + "this stuff, it tastes just like ginger ale."
            , "I'm a professional. I've had three performances."
            , "Oh, I'm so nervous. <br /><br />If I'm not funny, I won't be able "
                + "to live with myself."
            , "You don't go to Bombay to become a movie star! You go where we're "
                + "going: Hollywood."
            , "There was this sailor who was so fat! <br /><br /><i>[Nervously]</i>"
                + "Uh, he was so fat that everybody liked him and there was nothing "
                + "funny about him at all."
            , "If you think this crowd's ugly, you should see the dancing girls"
            , "Wow, that was such an expensive looking explosion! I can't believe "
                + "we had that in the budget!"
            , "What's more illegal, Kermit: briefly inconveniencing Jack Black, or "
                + "destroying the Muppets?"
            , "I went to this bad sea food place the other day. Yeah, it was so "
                + "bad, the catch of the day was salmon-ella!"
            , "<i>[as a portrait]</i> I didn't do it, I've been framed! Ah! "
                + "Wocka wocka!"
            , "Ah! Wocka wocka!"
            , "Sometimes I can be very persuasive."
        ]
    }
    ,{
        name:       "The Swedish Chef"
        , image:    "http://images1.wikia.nocookie.net/__cb20111104173209/muppet/"
            + "images/thumb/4/41/Swedish-chef.jpg/300px-Swedish-chef.jpg"
        , link:     "http://muppet.wikia.com/wiki/The_Swedish_Chef"
        , quotes:   [
            "Gersh gurndy morn-dee burn-dee, burn-dee, flip-flip-flip-flip"
                + "-flip-flip-flip-flip-flip."
            , "So, de beency bouncy burger, eh?"
            , "Bork! Bork! Bork!"
        ]
    }
    ,{
        name:       "Statler & Waldorf"
        , image:    "http://images2.wikia.nocookie.net/__cb20110325180960/muppet/"
            + "images/thumb/3/3d/TMS-Statler%26Waldorf-BalconyBox.jpg/"
            + "300px-TMS-Statler%26Waldorf-BalconyBox.jpg"
        , link:     "http://muppet.wikia.com/wiki/Statler_and_Waldorf"
        , quotes:   [
            "You think this show is educational? <br /><br />"
                + "<i>Yes, it will drive people to read books.</i>"
            , "It's one of those 3-D movies. Better put on your glasses.<br /><br />"
                + "<i>Hey, check out the guy in the Goofy mask. </i><br /><br />"
                + "That's no mask. <br /><br /><i>Ooops. Sorry, lady!</i>"
            , "You know, there's nothing like grand opera.<br /><br />"
                + "<i>Yep, and that was nothing like it</i>"
            , "I guess all's well that ends well. <br /><br />"
                + "<i>Doesn't matter to me, as long as it ends.</i>"
        ]
    }
    ,{
        name:       "Oscar the Grouch"
        , image:    "http://images2.wikia.nocookie.net/__cb52637/muppet/"
            + "images/thumb/c/c3/Oscar-can2.jpg/"
            + "130px-0%2C309%2C6%2C279-Oscar-can2.jpg"
        , link:     "http://muppet.wikia.com/wiki/Oscar_the_Grouch"
        , quotes:   [
            "Let this be the Grouch's cause!<br /><br />Point out everybody's "
                + "flaws! <br /><br />Something is wrong with everything, except "
                + "the way I sing!"
            , "This is where I wanna be - grouch paradise!<br /><br />"
                + "Just look it at. It's like a work of art!"
            , "Now that was television! Why can't they do shows like that more "
                + "often?<br /><br />Well it doesn't matter 'cause I taped it and "
                + "now I can watch it any time I want. <br /><br />I'm a lucky "
                + "grouch."
            , "I prefer recorded concerts on badly scratched records<br /><br />"
            , "I prefer colorized versions with lots and lots of commercial "
                + "interruptions!"
            , "Oh, well, I happen to like trash. I'll tell you what. <br /><br />"
                + "I'll give you this brand new broken portable TV for it, huh?"
                + "<br /><br />What do you say?"
            , "Aw, how's that for disgusting? If I watch anymore of this hugging, "
                + "I'm gonna get sick to my stomach! <br /><br />Let's get out of "
                + "here! <br /><br />But first, I've got to say that this revolting "
                + "spectacle was brought to you by the letters J and S and by the "
                + "number 6."
        ]
    }
    ,{
        name:       "Count von Count"
        , image:    "http://images3.wikia.nocookie.net/__cb20110619131712/muppet/"
            + "images/thumb/2/28/Count_Kneeling.png/316px-Count_Kneeling.png"
        , link:     "http://muppet.wikia.com/wiki/Count_von_Count"
        , quotes:   [
            "That's 278 incredible, colossal credits! Ha-Ha, I love motion pictures!"
            , "Follow that controversial talk show host!"
            , "One friend from Sesame Street, plus one friend from Sesame Street, "
                + "equals two friends from Sesame Street! <br /><br />Ah, ha, ha!"
        ]
    }
];