var thickofit = [
    {
        name:       "Malcolm Tucker"
        , image:    "http://www.comedy.co.uk/images/library/people/180x200/"
            + "t/thick_of_it_malcolm.jpg"
        , link:     "http://www.imdb.com/character/ch0029856/quotes"
        , quotes:   [
            "I'd love to stop and chat to you but I'd rather have type 2 diabetes."
            , "Relax, he has never hit anyone! Or at least anyone he's hit has "
                + "never had the bollocks to take it to a superior!"
            , "Keep you busy! You know, you have to keep the mind active at your "
                + "age."
            , "What's that sort of droning noise in the background there? What, "
                + "kind of boring, kind of low, sort of droning, boring, kind of "
                + "miserable, whining, kind of, sort of boring noise going on?"
            , "Stop fucking blinking! Or I will take your optic nerve and strangle "
                + "you with it! "
            , "Laurel and fucking Hardy! Glad you could join us. Did you manage to "
                + "get that piano up the stairs ok, yeah?"
            , "Of course I know! There's nothing that you know that I don't know. "
                + "I'm Doctor fucking Know."
            , "That is my mission. You, mister Nutty-Bar, have given me a task."
            , "I know it was you. You're a pint pot Judas."
            , "I am dealing with it, but oficially you're dealing with it, because "
                + "I don't wanna step on any toes."
            , "Oh look, don't start with the fucking semantics shit again. You know"
                + " what I call \"semantics\"? Wank!"
            , "Well it means that all the rats are now returning to a very buoyant "
                + "ship and a plain deck, so that's lovely, isn't it? "
            , "Look, half an hour ago you were in with a shot! This is half an hour"
                + " hence! We've fucking time-travelled, yes? We're in a weird and "
                + "wonderful world where everything is different! Maybe outside the"
                + " polar ice caps have melted! Maybe there's fucking robots "
                + "knocking about and Davina McCall is the new Pope! Maybe you can"
                + "download rice!"
            , " Now you see what I did there? I was both being funny and also "
                + "deadly serious."
            , "First, you've got no credentials. You're so back-bench, you've "
                + "actually fucking fallen off. You're out by the fucking bins where"
                + "I put you. Secondly, I'm gonna tell the Mirror about all the "
                + "drinking, and thirdly, I'm gonna tell the Mail about the affair "
                + "and fourthly, you've got a tiny head."
            , "What's that, cricket? That's the English equivalent of sport, isn't "
                + "it? No actual physical contact, just glaring."
            , "\Climbing the mountain of conflict\"? You sounded like a Nazi Julie "
                + "Andrews!"
            , "You sure you're working as hard as I am, 'cause I'm sweating spinal "
                + "fluid here!"
            , "Do I look like I've ever set foot in a stationery cupboard? I do all"
                + " my shagging in five-star hotels! "
            , "I've just come from a briefing with a nine-year-old child.<br />"
                + "His briefing notes were written in alphabetti spaghetti. When I "
                + "left, I nearly tripped up over his fucking umbilical cord."
            , "Don't get sarcastic with me, son. We burned this tight-arsed city to "
                + "the ground in 1814."
            , "You get sarcastic with me again and I will stuff so much cotton wool "
                + "down your fucking throat it'll come out your arse like the tail "
                + "on a Playboy bunny."
            , "Christ on a bendy-bus. Don't be such a fucking faff arse."
            , "You say nothing, okay? You stay detached. Otherwise that's what I'll "
                + "do to your retinas."
            , "Who was it that did your media training? Myra Hindley? It's terrible!"
                + "All these hands all over the place! You were like a sweaty "
                + " octopus trying to unhook a bra! It was like watching John "
                + "Leslie at work!"
            , "You and me, Ollie, hey? I just realised that we're on the same boat, "
                + "yeah?<br /><br />I mean, obviously, I'm up on the bridge with "
                + "the binoculars and the Richard Gere gear on, you're down in the"
                + " engine room trying not to get bum-raped by a bunch of big lads "
                + "with shovels, but, essentially, it's the same boat!"
            , "How dare you! How dare you! Don't you ever, EVER, call me a bully! "
                + "<br /><br />I'm so much worse than that."
            , "This is not the day for you to be brave with me, boy, let me tell "
                + "you that. You're no fucking Andy McNab."
            , "NOMFuP. <br />N-O-M-F-P. <br />Not My Fucking Problem. I quite like "
                + "that. Did you like that? I'll use that quite a lot today."
            , "You know me, I'm a man of principle, I like to know whether I'm "
                + "lying to save the skin of a tosser or a moron."
            , "But there is a difference between allowing someone's natural "
                + "tittishness to come through and just exploiting it through "
                + "camera work here! <br /><br />You're sticking one tit moment "
                + "on top of another tit moment! That wouldn't happen in real life!"
            , "He's so dense, that light bends around him."
            , "Get over here. Now. Might be advisable to wear brown trousers and a "
                + "shirt the colour of blood."
            , "I think we should use \"The Carrot and The Stick\" approach - you "
                + "take the carrot and you stick it up his fucking arse, followed "
                + "by the stick, followed by an even bigger, rougher carrot."
            , "What about the missus? Can we bring her out again? Well, she "
                + "basically has that thing of appearing to be a normal human "
                + "being, that seems to play well."
            , "No, he's useless, he's absolutely useless. No, he is. He's as "
                + "useless as a marzipan dildo."
            , "Fuck me! This is like a clown running across a minefield!"
            , "I mean, you carry on like this and I might not find you utterly "
                + "fucking contemptible."
            , "It IS possible to have a good resignation, you know!"
        ]
    }
    , {
        name:       "Rt Hon Nicola Murray MP"
        , image:    "http://www.comedy.co.uk/images/library/people/180x200/"
            + "t/thick_of_it_nicola.jpg"
        , link:     "http://www.imdb.com/character/ch0169571/quotes"
        , quotes:   [
            "So what should I be sitting on? Should I just get an upturned KFC "
                + "bucket?"
            , "Oh, great, I'm getting gang-bollocked"
            , "Katie's sixteen, she's the oldest. She's just left the school.<br />"
                + "She's a bit of a rebel. It's chiefly heroin. Although she has "
                + "cut down since getting pregnant by that Nigerian people "
                + "smuggler, because the track marks would have affected her porn "
                + "career."
            , "Somebody has just done a huge poo on my desk and I want it cleared "
                + "up."
            , "Can I just say that getting angry isn't gonna help anything. "
                + "I've done anger, I'm currently at grief, I'm working my way "
                + "towards bargaining, whatever, you know, you're behind me..."
            , "Where in the civil service guidelines does it say it's absolutely "
                + "fine to leave your minister alone with a hostile journalist, "
                + "if you just can't be arsed to walk down the stairs?"
            , "I could actually do without the theatrics I think, Malcolm."
            , "It's bonkers, isn't it? It's like trying to get through Israeli "
                + "customs wearing a t-shirt saying \"I heart bombing Israel\"."
            , "No swearing? Now we can all thank our fucky stars for that."
        ]
    }
    , {
        name:       "Glenn Cullen"
        , image:    "http://www.comedy.co.uk/images/library/people/180x200/"
            + "t/thick_of_it_glenn.jpg"
        , link:     "http://www.imdb.com/character/ch0029859/quotes"
        , quotes:   [
            "This is it, you know. This is where it begins. Who's in, who's out. "
                + "Fatty is out."
            , "So, you want me ring round every hotel in London and ask if anyone "
                + "of any name has booked in?"
            , "I'm supposed to be keeping Hugh abreast of everything but I'm "
                + "feeling about as up to date as a Gregorian calendar, I'm "
                + "completely out of the loop."
            , "This is a bucket of shit. If someone throws shit at us, we throw "
                + "shit back at them. <br />We start a shit fight. We throw so "
                + "much shit at them, that they can't pick up shit, they can't "
                + "throw shit, they can't do shit."
            , "On the outside chance she might just prefer to meet a human being, "
                + "I'm going down with you."
            , "I don't think that Malcolm saw my point of view. I got punched."
            , "It was the worst thing I've ever seen. And I was in 'Nam."
            , "So you want me to interrupt my holiday in a panic so Hugh doesn't "
                + "have to interrupt his holiday and look like he's panicking?"
            , "They only want him to make Cappucinos."
            , "What we need is something that the public want, is incredibly "
                + "popular and is free."
            , "Hating is better than laughing. Trust me."
        ]
    }
    , {
        name:       "Oliver Reeder"
        , image:    "http://www.comedy.co.uk/images/library/people/180x200/"
            + "t/thick_of_it_ollie.jpg"
        , link:     "http://www.imdb.com/character/ch0029857/quotes"
        , quotes:   [
            "Don't tell me he's gone feral, 'cause he was fucking terrifying "
                + "when you had him on the leash!"
            , "At least he'll spend more time with his fridge."
            , "I'm Tickety Fockety Boo, thank you very much!"
            , "Surely he's going to be unopposed. They'll be re-branding him "
                + "as we speak, I would imagine. New hair, Ted Baker teeth, all "
                + "the modern trappings of your political leader."
            , "Ah, no, that's the flush of the automatic urinals in the "
                + "gentelman's lavatory."
            , "He's doing the blinky thing again."
            , "Alright, the minute any chicken blood turns up on the paperwork "
                + "I'll be straight onto you, don't worry."
            , "Yeah, you think it's my finger, bitch."
            , "Oh, right, sorry, I just didn't want to interrupt. Never know what "
                + "you're doing in here."
            , "When I met you this morning I thought you were the nice Scot."
            , "Who wants to go and watch bollockvision?"
            , "Is that honestly the best swearing you can come up with?"
            , "On the scrap heap at the tender age of 76, it's no life for you, "
                + "is it - Glenn-nes. <br /><br />Hey, do you want me to call "
                + "Dignitas? I could call Indignitas. They could come around and "
                + "shove you out of the window, dressed as a clown."
            , "No, he'd hate that. He thinks of himself as a sort of thin white "
                + "Mugabe."
            , "No! No, I never use that word, let alone about you, no, absolutely, "
                + "I won't use it until, you know, it's been fully normalized and "
                + "has no further assosiation with the... female twat. "
            , "Alot of guys in a circle, all, you know... Well, I assume you don't "
                + "mean literally, do you? Presumably?"
            , "Sorry, I was just being romantic. Like I was ordered to by the "
                + "Romance Nazi."
            , "You know when your mom walked out, you think maybe it wasn't just "
                + "about your dad?"
        ]
    }
    , {
        name:       "Jamie"
        , image:    "http://www.comedy.co.uk/images/library/people/180x200/"
            + "t/thick_of_it_jamie.jpg"
        , link:     "http://www.imdb.com/character/ch0141880/quotes"
        , quotes:   [
            "You got a pretty fucking horsey face, and a bit of a horsey wife... "
            + "Are you a fucking horse? Are you?"
            , "You're a busted flush! You're not gonna be any Prime Minister, "
                + "you're not gonna be anything, so fuck off! "
            , "Well I'm asking nicely, but if necessary I could come and kidnap "
                + "you. I do keep a balaclava and gaffer tape in my car."
            , "No, no, he is a nice guy, it's just that apparently every eighteen "
                + "months, two years he burns out. Takes a truck booth full of "
                + "Prozac to get him righted."
            , "Kiss my bollocks, this has got nothing to do with me!"
            , "I think Watford will get bumped by the fact that we're about to hand "
                + "the nuclear codes to a guy who, every now and then, loses it so "
                + "bad he needs SatNav to find his own nipples."
            , "I tell you, if you think he's leaking now, wait till you see him when "
                + "I'm finished with him! He'll look like fucking Mel Gibson's Jesus!"
            , "It's not a proper cigar! Proper cigars are those big Cuban whoppers, "
                + "that is just a jumped up fag."
            , "What did you expect? They're builders! Have you ever seen a film "
                + "where the hero is a builder? No, no, because they never fucking "
                + "turn up in the nick of time."
            , "That is your career. And I think it might be fucked, but let's just "
                + "check.<br /><br />Yeah, yeah, it's pretty fucked.<br />Now, I "
                + "hope you can play the spoons, because you're too old to go back "
                + "to being a gentleman's fluffer."
        ]
    }
    , {
        name:       "Rt Hon Steve Fleming MP"
        , image:    "http://shadesofcaruso.files.wordpress.com/2010/10/"
            + "stevefleming.jpg"
        , link:     "http://en.wikiquote.org/wiki/The_Thick_of_It"
            + "#Series_3.2C_Episode_7"
        , quotes:   [
            "We are gonna take you down, down to Funky Town! Funky Town Central, "
                + "here we come! Choo-fucking-choo!"
            , "Choo-fucking-choo!"
            , "The show's over, it's curtains."
            , "Everyone knows we don't get on. We are the Gallagher brothers of "
                + "politics."
            , "Would you PLEASE fucking well...sorry. I lost my temper. <br />"
                + "Where is it? Where is it? Where is it? Oh, I've found it again, "
                + "it's all right! Always in the last place you look, eh?"
        ]
    }
    , {
        name:       "Stewart Pearson"
        , image:    "http://press.bbcamerica.com/media/2012/03/20/08_02---thumb.jpg"
        , link:     "http://www.imdb.com/character/ch0120040/quotes"
        , quotes:   [
            "Just wondering whether you're fully conversive with the new line, "
                + "whether you're really up to speed."
            , "So, what we're thinking... shirt outside the trowsers."
            , "We can do that. We can just seal this in. Contain the toxicity. "
                + "Chernobyl FM."
            , "Peter, you appear to have a car radio attached to your bath."
            , "Let's imagineer the narrative..."
        ]
    }
    , {
        name:       "Rt Hon Peter Mannion MP"
        , image:    "http://www.comedy.co.uk/images/library/people/180x200/"
            + "t/thick_of_it_peter.jpg"
        , link:     "http://en.wikiquote.org/wiki/The_Thick_of_It"
        , quotes:   [
            "You're looking well... for someone twice your age. Any news on the "
                + "aneurism?"
            , "What flavour of nut-brown piss are you going to pour in my ear?"
            , "She's useless, she knows nothing. You two would get on."
            , "The stupid one keeps staring at me."
            , "I'm sensing a change in management styles. From touchy-feely to "
                + "smashy-testes."
        ]
    }
    , {
        name:       "Rt Hon Hugh Abbott MP"
        , image:    "http://www.comedy.co.uk/images/library/people/180x200/"
            + "t/thick_of_it_hugh.jpg"
        , link:     "http://en.wikiquote.org/wiki/The_Thick_of_It"
        , quotes:   [
            "I'm not quite sure what level of reality I'm supposed to be "
                + "operating on."
            , "I work, I eat, I shower. That's it. Occasionally... I take a dump, "
                + "just as a sort of treat. <br />I mean, that really is my treat. "
                + "That's what it's come to. <br /><br />I sit there and I think, "
                + "\"No, I'm not going to read The New Statesman. This time is just "
                + "for me. This is quality time just for me.\" <br />Is that normal?"
            , "He's calling me the political equivalent of the house wine at a "
                + "suburban Indian restaurant."
            , "All events are regional. Everything that happens in the world has to "
                + "happen somewhere. Do you see? Even JFK's assassination was a "
                + "regional event. But it was also very important. Like this factory"
                + " visit."
            , "You saw me in there. I was swinging like a colostomy bag."
        ]
    }
    , {
        name:       "Terri Coverley"
        , image:    "http://www.comedy.co.uk/images/library/people/180x200/"
            + "t/thick_of_it_terri.jpg"
        , link:     "http://en.wikiquote.org/wiki/The_Thick_of_It"
        , quotes:   [
            "We don't exchange insults with bloody Simon arsepipes titty-twat."
            , "Well it was a bit of a shock for us. In a good way. Like twins or a "
                + "tax rebate."
            , "The problem is that if you say to a journalist, \"Can you avoid that "
                + "topic?\", that's when they really go for it. <br />It's like "
                + "saying to the school bully, \"I'll wet myself if you tickle me.\""
            , "That is a complete disaster. There will be nothing on television for "
                + "weeks now."
            , "It's very rude that, isn't it. I was always told never to make "
                + "personal remarks about people."
        ]
    }
];