var thickofit = [
    {
        name:       "Malcolm Tucker"
        , image:    "http://www.comedy.co.uk/images/library/people/180x200/"
            + "t/thick_of_it_malcolm.jpg"
        , link:     "http://www.imdb.com/character/ch0029856/quotes"
        , quotes:   [
            "I'd love to stop and chat to you but I'd rather have type 2 diabetes."
            , "Relax, he has never hit anyone! Or at least anyone he's hit has "
                + "never had the bollocks to take it to a superior!"
            , "Keep you busy! You know, you have to keep the mind active at your "
                + "age."
            , "What's that sort of droning noise in the background there? What, "
                + "kind of boring, kind of low, sort of droning, boring, kind of "
                + "miserable, whining, kind of, sort of boring noise going on?"
            , "Stop fucking blinking! Or I will take your optic nerve and strangle "
                + "you with it! "
            , "Laurel and fucking Hardy! Glad you could join us. Did you manage to "
                + "get that piano up the stairs ok, yeah?"
            , "Of course I know! There's nothing that you know that I don't know. "
                + "I'm Doctor fucking Know."
            , "That is my mission. You, mister Nutty-Bar, have given me a task."
            , "I know it was you. You're a pint pot Judas."
            , "I am dealing with it, but oficially you're dealing with it, because "
                + "I don't wanna step on any toes."
            , "Oh look, don't start with the fucking semantics shit again. You know"
                + " what I call \"semantics\"? Wank!"
            , "Well it means that all the rats are now returning to a very buoyant "
                + "ship and a plain deck, so that's lovely, isn't it? "
            , "Look, half an hour ago you were in with a shot! This is half an hour"
                + " hence! We've fucking time-travelled, yes? We're in a weird and "
                + "wonderful world where everything is different! Maybe outside the"
                + " polar ice caps have melted! Maybe there's fucking robots "
                + "knocking about and Davina McCall is the new Pope! Maybe you can"
                + "download rice!"
            , " Now you see what I did there? I was both being funny and also "
                + "deadly serious."
            , "First, you've got no credentials. You're so back-bench, you've "
                + "actually fucking fallen off. You're out by the fucking bins where"
                + "I put you. Secondly, I'm gonna tell the Mirror about all the "
                + "drinking, and thirdly, I'm gonna tell the Mail about the affair "
                + "and fourthly, you've got a tiny head."
            , "What's that, cricket? That's the English equivalent of sport, isn't "
                + "it? No actual physical contact, just glaring."
            , "\Climbing the mountain of conflict\"? You sounded like a Nazi Julie "
                + "Andrews!"
            , "You sure you're working as hard as I am, 'cause I'm sweating spinal "
                + "fluid here!"
            , "Do I look like I've ever set foot in a stationery cupboard? I do all"
                + " my shagging in five-star hotels! "
            , "I've just come from a briefing with a nine-year-old child.<br />"
                + "His briefing notes were written in alphabetti spaghetti. When I "
                + "left, I nearly tripped up over his fucking umbilical cord."
            , "Don't get sarcastic with me, son. We burned this tight-arsed city to "
                + "the ground in 1814."
            , "You get sarcastic with me again and I will stuff so much cotton wool "
                + "down your fucking throat it'll come out your arse like the tail "
                + "on a Playboy bunny."
            , "Christ on a bendy-bus. Don't be such a fucking faff arse."
            , "You say nothing, okay? You stay detached. Otherwise that's what I'll "
                + "do to your retinas."
            , "Who was it that did your media training? Myra Hindley? It's terrible!"
                + "All these hands all over the place! You were like a sweaty "
                + " octopus trying to unhook a bra! It was like watching John "
                + "Leslie at work!"
            , "You and me, Ollie, hey? I just realised that we're on the same boat, "
                + "yeah?<br /><br />I mean, obviously, I'm up on the bridge with "
                + "the binoculars and the Richard Gere gear on, you're down in the"
                + " engine room trying not to get bum-raped by a bunch of big lads "
                + "with shovels, but, essentially, it's the same boat!"
            , "How dare you! How dare you! Don't you ever, EVER, call me a bully! "
                + "<br /><br />I'm so much worse than that."
            , "This is not the day for you to be brave with me, boy, let me tell "
                + "you that. You're no fucking Andy McNab."
            , "NOMFuP. <br />N-O-M-F-P. <br />Not My Fucking Problem. I quite like "
                + "that. Did you like that? I'll use that quite a lot today."
            , "You know me, I'm a man of principle, I like to know whether I'm "
                + "lying to save the skin of a tosser or a moron."
            , "But there is a difference between allowing someone's natural "
                + "tittishness to come through and just exploiting it through "
                + "camera work here! <br /><br />You're sticking one tit moment "
                + "on top of another tit moment! That wouldn't happen in real life!"
            , "He's so dense, that light bends around him."
            , "Get over here. Now. Might be advisable to wear brown trousers and a "
                + "shirt the colour of blood."
            , "I think we should use \"The Carrot and The Stick\" approach - you "
                + "take the carrot and you stick it up his fucking arse, followed "
                + "by the stick, followed by an even bigger, rougher carrot."
            , "What about the missus? Can we bring her out again? Well, she "
                + "basically has that thing of appearing to be a normal human "
                + "being, that seems to play well."
            , "No, he's useless, he's absolutely useless. No, he is. He's as "
                + "useless as a marzipan dildo."
            , "Fuck me! This is like a clown running across a minefield!"
            , "I mean, you carry on like this and I might not find you utterly "
                + "fucking contemptible."
            , "It IS possible to have a good resignation, you know!"
        ]
    }
];