var westwing = [
    {
        name:       "Leo McGarry"
        , image:    "http://westwing.bewarne.com/characters/char_leo.jpg"
        , link:     "http://westwing.bewarne.com/leo.html"
        , quotes:   [
            "I don't like dealing with people who are trying to impress me."
            , "I take my daughter to a seafood place the first thing she does is "
                + "name all the lobsters in the tank so I can't eat 'em."
            , "I don't understand people who have one drink. I don't understand "
                + "people who leave half a glass of wine on the table.<br /><br />"
                + "I don't understand people who say they've had enough. <br />How "
                + "can you have enough of feeling like this? How can you not want "
                + "to feel like this longer?<br /><br />My brain works differently."
            , "You have an interesting conversational style, do you know that?"
            , "The President likes smart people who disagree with him.<br /><br />"
                + "He wants to hear from you."
            , "Margaret, please call the editor of the New York Times crossword and"
                + "tell him that Khaddafi is spelled with an H and two D's and isn't"
                + "a seven-letter word for anything."
            , "There has been a time in the evolution of everything that works when "
                + "it didn't work."
            , "I can't believe I didn't commit that piece of arcane information "
                + "to memory."
            , "A ship in the harbor is safe. But that's not what ships were built "
                + "for."
            , "I am making a mental list of those who are snickering, and even as I "
                + "speak I am preparing appropriate retribution."
            , "All right! Shut the hell up everybody. I've fired more people than "
                + "you before breakfast."
            , "You know, sometimes, I don't even know what you're talking about."
            , "I've got to keep the knucklehead stuff off his desk, and this is "
                + "worse.<br /><br />This is actually hot-button knucklehead..."
            , "My generation never got the future it was promised... <br />"
                + "Thirty-five years later, cars, air travel is exactly the same."
                + "We don't even have the Concorde anymore. Technology stopped."
                + "<br /><br />A more efficient delivery system for gossip and "
                + "pornography? Where's my jet pack, my colonies on the Moon?"
            , "Somebody needs to teach me about this."
            , "There are two things in the world you never want to let people "
                + "see how you make 'em - laws and sausages."
            , "You can't be taken down by this cheap person."
            , "This guy's walking down a street when he falls in a hole. The walls"
                + " are so steep, he can't get out. <br /><br />A doctor passes by, "
                + "and the guy shouts up, 'Hey you, can you help me out?'<br /> "
                + "The doctor writes a prescription, throws it down in the hole and"
                + " moves on.<br /><br />Then a priest comes along, and the guy "
                + "shouts up 'Father, I'm down in this hole, can you help me out?'"
                + "<br />The priest writes out a prayer, throws it down in the hole"
                + " and moves on.<br /><br />Then a friend walks by.<br />'Hey Joe, "
                + "it's me, can you help me out?'<br />And the friend jumps in the "
                + "hole.<br />Our guy says, 'Are you stupid? Now we're both down "
                + "here.'<br /><br />The friend says, 'Yeah, but I've been down here"
                + " before, and I know the way out.'"
        ]
    }
    , {
        name:       "Toby Ziegler"
        , image:    "http://westwing.bewarne.com/characters/char_toby.jpg"
        , link:     "http://westwing.bewarne.com/toby.html"
        , quotes:   [
            "There's literally no one in the world that I don't hate right now."
            , "All of a sudden I became the kid in the classroom with his hand "
                + "raised that no one wants the teacher to call on."
            , "I'm told that on my sunniest of days, I'm not that fun to be around."
            , "Have you fallen on your head?<br /><br />Have you fallen down and "
                + "hit your head on something hard?"
            , "Something really kinda freakish about you, you know that?"
            , "You're gonna lose, and you're gonna lose huge. <br />They're gonna "
                + "throw rocks at you next week, and I wanted to be standing next "
                + "to you when they did."
            , "I'm going to make a suggestion which might help you out, but I don't "
                + "want this gesture to be mistaken for an indication that I like "
                + "you."
            , "Sarcasm's a disturbing thing coming from a woman of your age."
            , "I hate these people with the heat of a nova."
            , "You want to know the benefits of free trade? Food is cheaper.<br />"
                + "<br />Food is cheaper! Clothes are cheaper. Steel is cheaper. "
                + "Cars are cheaper. Phone service is cheaper. <br />You feel me "
                + "building a rhythm here? That's because I'm a speech writer - I "
                + "know how to make a point.<br /><br />It lowers prices, it raises "
                + "income.<br />You see what I did with 'lowers' and 'raises' there?"
                + "<br />It's called the science of listener attention. We did "
                + "repetition, we did floating opposites, and now you end with the "
                + "one that's not like the others.<br /><br />Ready?<br /><br />"
                + "Free trade stops wars. Heh, and that's it.<br />Free trade stops "
                + "wars! And we figure out a way to fix the rest. "
            , "You want to tempt the wrath of the whatever from high atop the thing?"
                + "<br />Then go outside, turn around three times and spit. What "
                + "the hell's the matter with you?"
            , "Listen, when you get home tonight you're going to be confronted by "
                + "the instinct to drink alone. Trust that instinct. Manage the pain."
                + " Don't try to be a hero."
            , "I don't know from where you get the idea that taxpayers shouldn't "
                + "have to pay for anything of which they disapprove. Lots of 'em "
                + "don't like tanks..."
            , "By and large, I'm not wild about musicals."
            , "it's not the ones we lose that bother me, Leo. It's the ones we don't"
                + "suit up for."
            , "See, I lent voice to thought and that was my mistake."
            , "No, I'm disagreeing with you. That doesn't mean I'm not listening to "
                + "you or understanding what you're saying - I'm doing all three at "
                + "the same time."
            , "And you got to ask yourself, if no one on the Internet wants a piece "
                + "of this, just how far from the pack have you strayed?"
            , "I didn't realize babies come with hats."
            , "In fact, it doesn't say that at all. The only way it says that is if "
                + "you remove some words from it."
            , "I feel that I didn't have the opportunity to properly articulate "
                + "my argument."
        ]
    }
    , {
        name:       "Josh Lyman"
        , image:    "http://westwing.bewarne.com/characters/char_josh.jpg"
        , link:     "http://westwing.bewarne.com/josh.html"
        , quotes:   [
            "I'm holding your underwear in my hand right now. And the way I know "
                + "it's your underwear is that your name is sewn in the back which, "
                + "obviously, we'll spend some time talking about at a later date."
            , "Uh, uh, 'post' - after, after hoc, 'ergo' - therefore, 'After hoc, "
                + "therefore' something else hoc."
            , "Victory is mine, victory is mine. Great day in the morning, people, "
                + "victory is mine.<br /><br />I drink from the keg of glory, "
                + "Donna. Bring me the finest muffins and bagels in all the land."
            , "Why are you asking me the question when you're gonna have the "
                + "conversation all by yourself?"
            , "I want to be a comfort to my friends in tragedy and I want to be "
                + "able to celebrate with them in triumph. <br /><br />And for all "
                + "the times in between, I just want to be able to look them in the "
                + "eye."
            , "Right. Can we clear up a few things about my level of interest in "
                + "the revolving door of local Gomers that you see in the free "
                + "time you create by not working very hard at your job?"
            , "You're asking me to do that which I don't want to do, right?"
            , "You tend to call some bizarre factoid from a less-than-reputable "
                + "source and then you blow it all out of proportion."
            , "We think if we hit the ground hard enough, we can make it to the "
                + "center of the planet and find water?<br /><br />hat's not a "
                + "theory of physics pretty much disproved by Wile E. Coyote?"
            , "I'd like to clear up that I don't have suits for days of the week. "
                + "This is just a regular suit."
            , "You know what this is like?<br />This is like The Godfather when "
                + "Pacino tells James Caan that he's going to kill the cop. It's "
                + "a lot like that scene only not really."
            , "Hey, what did I say about speaking to me without addressing me as "
                + "'Wild Thing'?"
            , "Could I get *five* minutes without being interrupted by banality?"
            , "That's a permeating syllogism, to be sure."
            , "When I get back, you're gonna argue with me and we're gonna argue "
                + "about the things I wanna argue about and you're gonna do your "
                + "best not to annoy me too much."
            , "I got it. I read it. It was good stuff. It's possible the salient "
                + "details escape me."
            , "You're not going to be taken down by this small fraction of a man. "
                + "I won't permit it."
        ]
    }
    , {
        name:       "Sam Seaborn"
        , image:    "http://westwing.bewarne.com/characters/char_sam.jpg"
        , link:     "http://westwing.bewarne.com/sam.html"
        , quotes:   [
            "I argue for a living."
            , "No, honestly, I am dumb. Most of the time I'm playing smart."
            , "All right, my day was a little bit better a few seconds ago, but "
                + "that's all right."
            , "Education is the silver bullet. Education is everything.<br />We "
                + "don't need little changes, we need gigantic, monumental changes."
                + "<br /><br />Schools should be palaces. The competition for the "
                + "best teachers should be fierce. They should be making six-figure "
                + "salaries. <br />Schools should be incredibly expensive for "
                + "government and absolutely free of charge to its citizens, just "
                + "like national defense.<br /><br />That's my position. I just "
                + "haven't figured out how to do it yet."
            , "There are a lot of hungry people in the world, Mal, and none of "
                + "them are hungry 'cause we went to the moon. None of them are "
                + "colder and certainly none of them are dumber 'cause we went to "
                + "the moon."
            , "'Cause it's next. 'Cause we came out of the cave, and we looked over "
                + "the hill and we saw fire; and we crossed the ocean and we "
                + "pioneered the west, and we took to the sky.<br /><br />The "
                + "history of man is hung on a timeline of exploration and this is "
                + "what's next."
            , "Kazakhstan's a country four times the size of Texas and has a "
                + "sizable number of former Russian missile silos.<br />Kyrgyzstan's"
                + " on the side of a hill near China and has mostly nomads and sheep."
            , "You've got to ask yourself which is more exciting - watching your car "
                + "roll over from 99,999 to 100,000 or watching it go from one "
                + "hundred to a hundred and one."
            , "It turns out the majority of pennies don't circulate. They go in jars"
                + " and sock drawers. Two-thirds of the pennies produced in the last"
                + " 30 years have dropped out of circulation."
            , "Yeah, but I'm on the side of the angels."
            , "Do you really think it's a good idea to invite people to dinner and "
                + "then to tell them exactly what they're doing wrong with their "
                + "lives?"
            , "I don't think it's such a good idea to be casual about the truth."
            , "Oratory should raise your heart rate. Oratory should blow the doors "
                + "off the place. We should be talking about not being satisfied "
                + "with past solutions; we should be talking about a permanent "
                + "revolution."
            , "I'm less visually observant than others, but I make up for it, with "
                + "cunning and guile."
            , "That was pretty impressive, though it was an Aristotelian confluence "
                + "of events that could only happen to me."
            , "If I'm going to lose, I'd like to lose doing something."
            , "I think you're going to find as you go through this weekend, that "
                + "there's virtually no part of this discussion that isn't bizarre."
            , "If I were arrested for coveting my neighbor's wife, when asked about "
                + "it, I'd probably bear false witness."
        ]
    }
    , {
        name:       "C.J. Cregg"
        , image:    "http://westwing.bewarne.com/characters/char_cj.jpg"
        , link:     "http://westwing.bewarne.com/cj.html"
        , quotes:   [
            "You think you get it wrong sometimes, you should come down here and "
                + "see how the big boys do it."
            , "You get my support the same way I get yours: when I agree with what "
                + "you're saying or when I don't care about what you're saying.<br />"
                + "This time I disagreed."
            , "Oh, Holy Interruptus, Batman!"
            , "It's about damn time you asked me! I've been sitting here for two "
                + "weeks turning down all kinds of very, frankly, glamorous "
                + "invitations from people I like a lot more than you!<br /> You "
                + "can't ask a girl at the last minute..."
            , "And, by God, you were home by supper on a school night."
            , "You want to make out with me right now, don't you?"
            , "I rode the life-cycle this morning for an hour and a half. <br />"
                + "If it was a real cycle I'd have been in Belgium by now."
            , "If we're about freedom from tyranny, then we're about freedom from "
                + "tyranny, and if we're not, we should shut up."
            , "I wanna do my job. I wanna suck every morsel of meat off this "
                + "experience before it's over."
            , "I should punch you in the face."
            , "Men are like salmon. Swimming upstream, hosing down the riverbed "
                + "with their indiscriminate seed..<br /><br />Until they die, "
                + "bloated and spent, belly-up in the sun.<br /><br />Unless they "
                + "get taken out with a bear paw in the waterfall, as they deserve "
                + "to be."
            , "When you flirt with me, are you doing it to get a story?"
            , "Set fire to the room. Do it now."
            , "Number of people killed last year retrieving change from a vending "
                + "machine: four.<br />Number of people killed by a wolf attack: "
                + "zero."
            , "It's the fall that's gonna kill ya."
            , "I have the ancient curse of Bast, on me, OK? So back off, Sparky."
            , "The theme of this year's event is, 'learning is delightful and "
                + "delicious' - as, by the way, am I."
            , "Boy, boy, crazy boy, keep cool, boy."
        ]
    }
    , {
        name:       "Josiah Bartlett"
        , image:    "http://westwing.bewarne.com/characters/char_potus.jpg"
        , link:     "http://westwing.bewarne.com/pres.html"
        , quotes:   [
            "Seriously, when they were telling you that on the phone, how stupid "
                + "did you think you'd sound saying it to me?"
            , "I'm victim to my own purity of character."
            , "Never doubt that a small group of thoughtful committed citizens "
                + "can change the world."
            , "Jokes like that are part of my folksy charm, Morris. It's at the "
                + "very heart of my popularity."
            , "Just be wrong. Just stand there in your wrongness and be wrong "
                + "and get used to it."
            , "What I lack in memory, I more than make up for with exceptional "
                + "powers of deductive reasoning."
            , "Look, obviously we knew that this was going to be a thing, but "
                + "it doesn't have to be tonight, right?"
            , "'We hold these truths to be self-evident,' they said, 'that all "
                + "men are created equal.'<br />Strange as it may seem, that was "
                + "the first time in history that anyone had ever bothered to "
                + "write that down.<br /><br />Decisions are made by those who "
                + "show up."
            , "When somebody tries to explain cricket to me, all I want to do is "
                + "hit him in the head with a teapot."
            , "I'm going to tell you a story and I want you to tell me if I've "
                + "engaged 16 people in a conspiracy to defraud the public in "
                + "order to win a Presidential election."
            , "Is this a joke? If it's a joke, it's both funny and well-executed. "
                + "<br /><br />But I think you and I both know that it's not."
            , "The things we choose to care about."
            , "When they close the book on me and you, it will say that at this "
                + "moment you were not there for me. And for that, obviously, "
                + "there will be some kind of punishment."
            , "Your impersonation of my mother is getting sharper and sharper, "
                + "you know that?"
            , "I hear things. I don't understand most of it, but I hear it."
            , "Shaken, not stirred, will get you cold water with a dash of gin and "
                + "dry vermouth. The reason you stir it with a special spoon is so "
                + "not to chip the ice. James is ordering a weak martini and being "
                + "snooty about it."
            , "I was wrong. I was, I was just... I was wrong.<br />Come on, we know "
                + "that.<br /><br />Lots of times we don't know what right or wrong "
                + "is, but lots of times we do, and come on... this is one. I may "
                + "not have had sinister intent at the outset, but there were "
                + "plenty of opportunities for me to make it right."
            , "All this posturing is a preamble to something."
            , "I don't know what's worse: being stupid, or pretending to be stupid."
            , "It's not hard to like a guy when he's doing well. The measure of a "
                + "man is how does he behave when things are otherwise?"
            , "You know what the difference is between you and me? I want to be "
                + "the guy. You want to be the guy the guy counts on."
            , "When you walk out of here, there'll be people out there, perhaps a "
                + "great many, who'll think of you as a hero. I just don't for a "
                + "moment want you thinking I'll be one of them."
        ]
    }
];